#!/usr/bin/env bash
usage="Usage:
 mobby [grab|share|remain|new|finish]"
# if no command, print usage
if [ -z "${1+x}" ]; then
  cowsay "$usage"
  exit
fi

# if we want to grab, then git pr and set mob timer to 10 minutes
if [ "$1" == "grab" ]; then
  git pull --rebase
  cowsay "Go Driver, Go!"
  (sleep 600 && cowsay "Time to Switch" && say "Time to switch") &
  exit
fi

# if we want to share, then git commit with a with and push
if [ "$1" == "share" ]; then
  if [[ -v 2 ]]; then
    git commit -am "WIP: $2"
  else
    git commit -am "WIP"
  fi
  git push
  exit
fi

# if we want to rebase on main
if [ "$1" == "remain" ]; then
  git checkout main
  git pull --rebase
  git checkout -
  git rebase main
  git push --force-with-lease
  exit
fi

#if we want to start a new branch
if [ "$1" == "new" ]; then
  git checkout -b "$2"
  git push --set-upstream origin "$2"
  exit
fi

#when we are done with the branch
if [ "$1" == "finish" ]; then
  git checkout main
  git pull --rebase
  git checkout -
  git rebase main
  git commit --allow-empty
  git rebase -i main
  exit
fi

cowsay "$usage"
