name: CI

on:
  push:
    branches:
      - porceline

jobs:
  nix:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      # Your Nix build steps
      - name: Build with Nix
        run: nix build
